### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Suomea** [SiGuiyang/spring-cloud-shop#5]
我点击商品管理-》商品配置的时候，后台报错：
![image](https://user-images.githubusercontent.com/26758537/65585159-9a755980-dfb4-11e9-99cf-da06b9c24d8d.png)
然后我对了一下 sql 语句和 model，发现好像 t_goods 表中有一个 description 字段，而在 quick.pager.shop.model.goods.Goods 类中没有对应的属性。

**Comment by Suomea** [comment]
好像还不止一个对不上，是我的版本有问题吗？

**Comment by SiGuiyang** [comment]
hi，这个不是版本的问题，商品中心与订单中心这两块的核心业务还没有想好怎么设计。这块核心业务将会在10月底前更新上

**Comment by SiGuiyang** [comment]
> 好像还不止一个对不上，是我的版本有问题吗？
hi，这个不是版本的问题，商品中心与订单中心这两块的核心业务还没有想好怎么设计。这块核心业务将会在10月底前更新上
